export const getConfigurableProps = () => ({
    showArrows: true,
    showStatus: true,
    showIndicators: true,
    infiniteLoop: true,
    showThumbs: false,
    useKeyboardArrows: true,
    autoPlay: true,
    stopOnHover: true,
    swipeable: true,
    dynamicHeight: false,
    emulateTouch: true,
    autoFocus: false,
    selectedItem: 0,
    interval: 3000,
    transitionTime: 500,
    swipeScrollTolerance: 5,
    ariaLabel: undefined,
});